---

- name: Install the datanode packages
  sudo: yes
  yum: name={{item}} state=installed
  with_items: 
   - hadoop-hdfs-datanode
   - hadoop-lzo-cdh4
   - bigtop-utils

- name: Create the data directory for the datanode dir
  sudo: yes
  file: path={{item}} owner=hdfs group=hdfs state=directory
  with_items: hdfs__dfs_datanode_data_dir

- include: ../../jar/tasks/hadoop.yml
