

- include: ../../conf/tasks/namenode.yml

- name: start zkfc
  sudo: yes
  service: name=hadoop-hdfs-zkfc state=started

- name: start namenode
  sudo: yes
  service: name=hadoop-hdfs-namenode state=started


