---
# 分发hadoop配置
#
- hosts: all
  tasks:
  - include: roles/conf/tasks/hadoop.yml

- hosts: NAMENODE
  tasks:
  - include: roles/conf/tasks/namenode.yml

- hosts: RESOURCEMANAGER
  tasks:
  - include: roles/conf/tasks/resourcemanager.yml
